'use client';

import { useEffect, useState } from 'react';
import { usePathname, useRouter, useSearchParams } from 'next/navigation';
import type { BookingIntentDto } from '@/lib/checkout';

/** PROTOTYPE — Three ancillary layouts, switchable with ?variant=A|B|C. */

type Props = { intent: BookingIntentDto };
type Service = 'seats' | 'baggage';
type VariantKey = 'A' | 'B' | 'C';
type SeatTier = 'standard' | 'preferred' | 'extraLegroom' | 'premium';
type SeatStatus = 'available' | 'unavailable' | 'held';
type Seat = { id: string; tier: SeatTier; status: SeatStatus };

const variants: Array<{ key: VariantKey; name: string }> = [
  { key: 'A', name: 'Cabin studio' },
  { key: 'B', name: 'Focused journey' },
  { key: 'C', name: 'Travel wallet' },
];

const seatTiers: Record<SeatTier, { label: string; detail: string; price: number; className: string }> = {
  standard: { label: 'Standard', detail: 'Rear cabin', price: 18, className: 'seat-tier-standard' },
  preferred: { label: 'Preferred', detail: 'Quieter middle cabin', price: 26, className: 'seat-tier-preferred' },
  extraLegroom: { label: 'Extra legroom', detail: 'Exit-row space', price: 38, className: 'seat-tier-extra-legroom' },
  premium: { label: 'Front cabin', detail: 'Board and exit earlier', price: 54, className: 'seat-tier-premium' },
};

const seatRows: Seat[][] = [
  [['12A', 'premium', 'available'], ['12B', 'premium', 'available'], ['12C', 'premium', 'unavailable'], ['12D', 'premium', 'available'], ['12E', 'premium', 'available'], ['12F', 'premium', 'available']],
  [['13A', 'extraLegroom', 'available'], ['13B', 'extraLegroom', 'available'], ['13C', 'extraLegroom', 'available'], ['13D', 'extraLegroom', 'unavailable'], ['13E', 'extraLegroom', 'available'], ['13F', 'extraLegroom', 'available']],
  [['14A', 'preferred', 'available'], ['14B', 'preferred', 'available'], ['14C', 'preferred', 'available'], ['14D', 'preferred', 'available'], ['14E', 'preferred', 'available'], ['14F', 'preferred', 'held']],
  [['15A', 'standard', 'unavailable'], ['15B', 'standard', 'available'], ['15C', 'standard', 'available'], ['15D', 'standard', 'available'], ['15E', 'standard', 'available'], ['15F', 'standard', 'available']],
  [['16A', 'standard', 'available'], ['16B', 'standard', 'available'], ['16C', 'standard', 'available'], ['16D', 'standard', 'available'], ['16E', 'standard', 'available'], ['16F', 'standard', 'unavailable']],
].map((row) => row.map(([id, tier, status]) => ({ id, tier: tier as SeatTier, status: status as SeatStatus })));

function money(amount: number, currency: string): string {
  return new Intl.NumberFormat('en-US', { style: 'currency', currency, maximumFractionDigits: 0 }).format(amount);
}

function ServiceNav({ service, onChange }: { service: Service; onChange: (service: Service) => void }): JSX.Element {
  return <nav className="flex w-full gap-1 rounded-xl border border-card-border bg-card p-1 sm:w-fit" aria-label="Ancillary service">
    {(['seats', 'baggage'] as const).map((item) => <button key={item} type="button" onClick={() => onChange(item)} className={`flex-1 rounded-lg px-5 py-3 text-sm font-semibold transition sm:flex-none ${service === item ? 'bg-primary text-primary-foreground shadow-sm' : 'text-text-secondary hover:bg-background'}`} aria-current={service === item ? 'page' : undefined}>{item === 'seats' ? 'Seats' : 'Baggage'}</button>)}
  </nav>;
}

function SeatMap({ selectedSeat, onSelect, currency }: { selectedSeat: string | null; onSelect: (seat: string) => void; currency: string }): JSX.Element {
  return <section className="card space-y-6" aria-labelledby="seat-map-title">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-wider text-text-muted">Outbound · JFK to LHR</p><h2 id="seat-map-title" className="mt-1 text-2xl font-bold text-text-primary">Choose a seat for Jordan</h2><p className="mt-2 text-sm text-text-secondary">Colours show a seat type; the price guide makes the cost clear.</p></div><span className="rounded-full bg-secondary px-3 py-1 text-xs font-semibold text-text-secondary">Economy</span></div>
    <section className="rounded-2xl border border-card-border bg-background p-4" aria-labelledby="seat-price-guide-title"><div className="flex flex-wrap items-center justify-between gap-2"><h3 id="seat-price-guide-title" className="font-semibold text-text-primary">Seat price guide</h3><span className="text-xs text-text-muted">USD per traveller</span></div><ul className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{(Object.keys(seatTiers) as SeatTier[]).map((tier) => <li key={tier} className="flex items-center gap-3 text-sm"><span className={`h-8 w-8 rounded-lg border ${seatTiers[tier].className}`} aria-hidden="true" /><span><span className="block font-semibold text-text-primary">{seatTiers[tier].label} · {money(seatTiers[tier].price, currency)}</span><span className="block text-xs text-text-secondary">{seatTiers[tier].detail}</span></span></li>)}<li className="flex items-center gap-3 text-sm"><span className="seat-tier-unavailable flex h-8 w-8 items-center justify-center rounded-lg border" aria-hidden="true">×</span><span><span className="block font-semibold text-text-primary">Unavailable</span><span className="block text-xs text-text-secondary">Not selectable</span></span></li></ul></section>
    <div className="mx-auto max-w-xl rounded-[3rem] border border-card-border bg-background px-5 py-7 sm:px-10" role="grid" aria-label="Aircraft seat map"><div className="mb-5 flex justify-between px-3 text-xs font-semibold tracking-widest text-text-muted"><span>WINDOW</span><span>FRONT OF AIRCRAFT</span><span>WINDOW</span></div><div className="space-y-3">{seatRows.map((row) => <div key={row[0].id} className="grid grid-cols-[2.25rem_repeat(3,minmax(0,1fr))_1.25rem_repeat(3,minmax(0,1fr))] items-center gap-2" role="row"><span className="text-xs font-semibold text-text-muted">{row[0].id.slice(0, 2)}</span>{row.map((seat, index) => { if (index === 3) return <span key={`${seat.id}-aisle`} className="text-center text-xs text-text-muted">{seat.id.slice(0, 2)}</span>; const tier = seatTiers[seat.tier]; const chosen = selectedSeat === seat.id; const isAvailable = seat.status === 'available'; const state = seat.status === 'held' ? 'held by Alex Doe' : seat.status; return <button key={seat.id} type="button" role="gridcell" disabled={!isAvailable} onClick={() => onSelect(seat.id)} aria-pressed={chosen} aria-label={`${seat.id}, ${tier.label}, ${money(tier.price, currency)}, ${chosen ? 'selected for Jordan' : state}`} className={`relative aspect-square min-h-11 rounded-lg border text-xs font-bold transition focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary ${isAvailable ? tier.className : seat.status === 'held' ? 'cursor-not-allowed border-text-pending bg-bg-pending text-text-pending' : 'seat-tier-unavailable cursor-not-allowed'} ${chosen ? 'ring-4 ring-primary ring-offset-2 ring-offset-background' : ''}`}>{chosen ? '✓' : seat.status === 'unavailable' ? '×' : seat.status === 'held' ? '•' : seat.id.slice(-1)}</button>; })}</div>)}</div></div>
    <p className="text-xs text-text-secondary">✓ selected for Jordan · • selected by Alex · × unavailable. Selection and availability are also shown with symbols, not colour alone.</p>
  </section>;
}

function BaggageOptions({ bags, onChange, currency }: { bags: number; onChange: (bags: number) => void; currency: string }): JSX.Element {
  return <section className="space-y-5" aria-labelledby="baggage-title"><div><p className="text-xs font-semibold uppercase tracking-wider text-text-muted">Outbound + return</p><h2 id="baggage-title" className="mt-1 text-2xl font-bold text-text-primary">Baggage for the whole journey</h2><p className="mt-2 text-sm text-text-secondary">Choose once and your allowance follows you across every flight.</p></div>{[0, 1, 2].map((quantity) => { const active = quantity === bags; return <button key={quantity} type="button" onClick={() => onChange(quantity)} className={`card flex w-full items-center justify-between gap-5 text-left transition ${active ? 'border-primary ring-1 ring-primary' : 'hover:border-primary'}`} aria-pressed={active}><span className="flex items-center gap-4"><span className={`flex h-8 w-8 items-center justify-center rounded-full border text-sm font-bold ${active ? 'border-primary bg-primary text-primary-foreground' : 'border-card-border text-text-muted'}`}>{active ? '✓' : quantity}</span><span><span className="block font-bold text-text-primary">{quantity === 0 ? 'No extra bags' : `${quantity} checked bag${quantity === 1 ? '' : 's'}`}</span><span className="mt-1 block text-sm text-text-secondary">{quantity === 0 ? 'Keep the fare allowance' : `${quantity * 23} kg total · full journey`}</span></span></span><span className="font-bold text-text-primary">{quantity === 0 ? 'Included' : money(quantity * 52, currency)}</span></button>; })}<aside className="rounded-xl border border-card-border bg-background p-4 text-sm text-text-secondary"><span className="font-semibold text-text-primary">Why journey-wide?</span> It prevents duplicate purchases when an equivalent whole-trip option is available.</aside></section>;
}

function PriceSummary({ intent, selectedSeat, bags, layout = 'card' }: { intent: BookingIntentDto; selectedSeat: string | null; bags: number; layout?: 'card' | 'strip' }): JSX.Element {
  const selected = seatRows.flat().find((seat) => seat.id === selectedSeat); const tier = selected ? seatTiers[selected.tier] : null; const seatPrice = tier?.price ?? 0; const bagPrice = bags * 52; const total = intent.confirmedPrice + seatPrice + bagPrice;
  return <aside className={`${layout === 'card' ? 'card space-y-4 lg:sticky lg:top-6' : 'rounded-2xl border border-card-border bg-card p-4'}`} aria-label="Estimated total"><div className="flex items-center justify-between gap-5"><div><p className="text-xs font-semibold uppercase tracking-wider text-text-muted">Your estimate</p><p className="mt-1 text-2xl font-bold text-text-primary">{money(total, intent.currency)}</p></div><span className="text-right text-sm text-text-secondary">{selected ? `${selected.id} · ${tier?.label}` : 'No seat selected'}<br />{bags ? `${bags} bag${bags > 1 ? 's' : ''} added` : 'No extra bags'}</span></div>{layout === 'card' && <><dl className="space-y-2 border-t border-card-border pt-4 text-sm text-text-secondary"><div className="flex justify-between"><dt>Flight</dt><dd>{money(intent.confirmedPrice, intent.currency)}</dd></div><div className="flex justify-between"><dt>{tier ? `${tier.label} seat` : 'Seat'}</dt><dd>{money(seatPrice, intent.currency)}</dd></div><div className="flex justify-between"><dt>Baggage</dt><dd>{money(bagPrice, intent.currency)}</dd></div></dl><button type="button" className="btn-primary w-full" disabled>Continue (prototype)</button></>}</aside>;
}

type VariantProps = Props & { service: Service; setService: (service: Service) => void; selectedSeat: string | null; setSelectedSeat: (seat: string) => void; bags: number; setBags: (bags: number) => void };
function VariantA(props: VariantProps): JSX.Element { return <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_18rem]"><div className="space-y-6"><ServiceNav service={props.service} onChange={props.setService} />{props.service === 'seats' ? <SeatMap selectedSeat={props.selectedSeat} onSelect={props.setSelectedSeat} currency={props.intent.currency} /> : <BaggageOptions bags={props.bags} onChange={props.setBags} currency={props.intent.currency} />}</div><PriceSummary intent={props.intent} selectedSeat={props.selectedSeat} bags={props.bags} /></div>; }
function VariantB(props: VariantProps): JSX.Element { return <div className="mx-auto max-w-4xl space-y-6"><section className="rounded-3xl border border-card-border bg-card p-6 sm:p-9"><p className="text-xs font-semibold uppercase tracking-wider text-text-muted">Step 2 of 4 · Make it yours</p><h2 className="mt-2 text-3xl font-bold text-text-primary">One decision at a time.</h2><p className="mt-3 max-w-xl text-text-secondary">Seats and baggage live in their own focused destinations. Finish either in any order.</p><div className="mt-7"><ServiceNav service={props.service} onChange={props.setService} /></div></section>{props.service === 'seats' ? <SeatMap selectedSeat={props.selectedSeat} onSelect={props.setSelectedSeat} currency={props.intent.currency} /> : <BaggageOptions bags={props.bags} onChange={props.setBags} currency={props.intent.currency} />}<PriceSummary intent={props.intent} selectedSeat={props.selectedSeat} bags={props.bags} layout="strip" /></div>; }
function VariantC(props: VariantProps): JSX.Element { const cards: Array<{ key: Service; title: string; description: string }> = [{ key: 'seats', title: 'Find your seat', description: props.selectedSeat ? `Jordan is in ${props.selectedSeat}` : 'Pick a place in the cabin' }, { key: 'baggage', title: 'Plan your bags', description: props.bags ? `${props.bags} checked bag${props.bags > 1 ? 's' : ''} for the journey` : 'No extra bags yet' }]; return <div className="grid gap-6 lg:grid-cols-[17rem_minmax(0,1fr)]"><aside className="card h-fit space-y-3"><p className="text-xs font-semibold uppercase tracking-wider text-text-muted">Your travel wallet</p><h2 className="text-xl font-bold text-text-primary">JFK to LHR</h2>{cards.map((card) => <button key={card.key} type="button" onClick={() => props.setService(card.key)} className={`w-full rounded-xl border p-4 text-left transition ${props.service === card.key ? 'border-primary bg-secondary' : 'border-card-border hover:border-primary'}`}><span className="block font-bold text-text-primary">{card.title}</span><span className="mt-1 block text-sm text-text-secondary">{card.description}</span></button>)}<PriceSummary intent={props.intent} selectedSeat={props.selectedSeat} bags={props.bags} layout="strip" /></aside><div>{props.service === 'seats' ? <SeatMap selectedSeat={props.selectedSeat} onSelect={props.setSelectedSeat} currency={props.intent.currency} /> : <BaggageOptions bags={props.bags} onChange={props.setBags} currency={props.intent.currency} />}</div></div>; }

function PrototypeSwitcher({ current }: { current: VariantKey }): JSX.Element | null { const router = useRouter(); const pathname = usePathname(); const params = useSearchParams(); const index = variants.findIndex((item) => item.key === current); const cycle = (direction: -1 | 1): void => { const next = variants[(index + direction + variants.length) % variants.length]; const query = new URLSearchParams(params.toString()); query.set('variant', next.key); router.replace(`${pathname}?${query}`); }; useEffect(() => { const handler = (event: KeyboardEvent): void => { const element = event.target as HTMLElement | null; if (element?.matches('input, textarea, [contenteditable]')) return; if (event.key === 'ArrowLeft') cycle(-1); if (event.key === 'ArrowRight') cycle(1); }; window.addEventListener('keydown', handler); return () => window.removeEventListener('keydown', handler); }); if (process.env.NODE_ENV === 'production') return null; return <nav className="fixed bottom-5 left-1/2 z-50 flex -translate-x-1/2 items-center gap-3 rounded-full border border-card-border bg-card px-3 py-2 shadow-lg" aria-label="Prototype variant switcher"><button type="button" onClick={() => cycle(-1)} className="btn-secondary px-3" aria-label="Previous prototype variant">←</button><span className="min-w-40 text-center text-sm font-semibold text-text-primary">{current} — {variants[index].name}</span><button type="button" onClick={() => cycle(1)} className="btn-secondary px-3" aria-label="Next prototype variant">→</button></nav>; }

export function AncillarySelectionPrototype({ intent }: Props): JSX.Element { const router = useRouter(); const pathname = usePathname(); const params = useSearchParams(); const variant = variants.some((item) => item.key === params.get('variant')) ? params.get('variant') as VariantKey : 'A'; const service: Service = params.get('service') === 'baggage' ? 'baggage' : 'seats'; const [selectedSeat, setSelectedSeat] = useState<string | null>('12B'); const [bags, setBags] = useState(1); const setService = (next: Service): void => { const query = new URLSearchParams(params.toString()); query.set('service', next); router.replace(`${pathname}?${query}`); }; const common: VariantProps = { intent, service, setService, selectedSeat, setSelectedSeat, bags, setBags }; return <div className="space-y-6 pb-20"><header className="space-y-2"><p className="text-xs font-semibold uppercase tracking-wider text-text-pending">Development-only prototype</p><h1 className="text-3xl font-bold text-text-primary">Your flight extras</h1><p className="max-w-2xl text-text-secondary">Seats and baggage deliberately open as separate views. Each seat colour represents a transparent USD price tier.</p></header>{variant === 'A' && <VariantA {...common} />}{variant === 'B' && <VariantB {...common} />}{variant === 'C' && <VariantC {...common} />}<PrototypeSwitcher current={variant} /></div>; }
