/* eslint-disable @typescript-eslint/no-explicit-any */
import { currencyFormatter } from './types';

export function CancellationStatus({ booking, cancellationStatus }: { booking: any; cancellationStatus: any }) {
  if (!cancellationStatus || !['CANCELLATION_PENDING', 'CANCELLED_PENDING_REFUND', 'REFUND_FAILED_NEEDS_ATTENTION', 'CANCELLED_AND_REFUNDED', 'CANCELLED_NO_REFUND'].includes(booking.status)) return null;
  return <div className="bg-bg-secondary p-4 rounded-lg border border-border-primary">
    <h3 className="font-semibold text-text-primary mb-2">Cancellation Status</h3>
    <p className="text-sm text-text-secondary mb-1">Status: <span className="font-medium text-text-primary">{cancellationStatus.bookingStatus}</span></p>
    {cancellationStatus.customerRefundAmount && <p className="text-sm text-text-secondary mb-1">Expected Refund: <span className="font-medium text-text-primary">{currencyFormatter(cancellationStatus.customerRefundAmount, booking.currency)}</span></p>}
    {booking.status === 'REFUND_FAILED_NEEDS_ATTENTION' && <div className="mt-4 p-3 bg-danger-border/10 border border-danger-border rounded"><p className="text-sm font-semibold text-text-cancelled mb-2">{cancellationStatus.escalationMessage || 'Refund requires attention. Please contact support.'}</p><ul className="text-xs text-text-secondary space-y-1">{cancellationStatus.refundStatus && <li>Refund Status: {cancellationStatus.refundStatus}</li>}{cancellationStatus.retryCount !== null && <li>Retry Count: {cancellationStatus.retryCount}</li>}{cancellationStatus.lastErrorCode && <li>Last Error: {cancellationStatus.lastErrorCode}</li>}</ul></div>}
  </div>;
}

type ModalProps = { booking: any; quote: any; loadingQuote: boolean; error: string | null; confirmCancel: boolean; cancelling: boolean; onClose: () => void; onConfirmCancelChange: (checked: boolean) => void; onConfirm: () => void };
export function CancellationModal({ booking, quote, loadingQuote, error, confirmCancel, cancelling, onClose, onConfirmCancelChange, onConfirm }: ModalProps) {
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm p-4"><div className="bg-background border border-border-primary rounded-xl p-6 max-w-md w-full shadow-2xl"><h3 className="text-xl font-bold text-text-primary mb-4">Cancel Booking</h3>
    {loadingQuote ? <p className="text-text-secondary">Fetching cancellation quote...</p> : error ? <div><p className="text-text-cancelled mb-4">{error}</p><button onClick={onClose} className="px-4 py-2 bg-bg-secondary text-text-primary rounded hover:bg-border-primary transition-colors">Close</button></div> : quote ? <div className="space-y-4"><div className="bg-bg-secondary p-4 rounded-lg space-y-2"><div className="flex justify-between text-sm"><span className="text-text-secondary">Total Paid:</span><span className="font-medium text-text-primary">{currencyFormatter(booking.totalAmount, booking.currency)}</span></div><div className="flex justify-between text-sm"><span className="text-text-secondary">Refund Amount:</span><span className="font-medium text-text-primary">{currencyFormatter(quote.refundAmount, quote.currency)}</span></div><div className="flex justify-between text-sm text-text-cancelled"><span>Penalty / Fees:</span><span>{currencyFormatter((Number(booking.totalAmount) - Number(quote.refundAmount)).toString(), quote.currency)}</span></div></div><label className="flex items-start gap-2 cursor-pointer mt-4"><input type="checkbox" className="mt-1" checked={confirmCancel} onChange={(event) => onConfirmCancelChange(event.target.checked)} /><span className="text-sm text-text-secondary">I understand that this action cannot be undone and the refund amount is subject to airline policies.</span></label><div className="flex justify-end gap-3 mt-6"><button onClick={onClose} disabled={cancelling} className="px-4 py-2 bg-bg-secondary text-text-primary rounded hover:bg-border-primary transition-colors disabled:opacity-50">Go Back</button><button onClick={onConfirm} disabled={!confirmCancel || cancelling} className="px-4 py-2 bg-danger-border text-white rounded hover:bg-red-600 transition-colors disabled:opacity-50">{cancelling ? 'Cancelling...' : 'Confirm Cancellation'}</button></div></div> : null}
  </div></div>;
}
